[dist]
# CI backends to support
ci = "github"
# The preferred cargo-dist version to use
cargo-dist-version = "0.29.0"
# Target platforms
targets = [
    "aarch64-apple-darwin",
    "x86_64-apple-darwin",
    "x86_64-unknown-linux-gnu"
]
# Installers to generate
installers = ["homebrew"]
# Publish to Homebrew tap
tap = "anthonyamaro15/homebrew-tap"
# Formula name
formula = "ff"
# The archive format to use
unix-archive = ".tar.gz"
